# Generated by Django 2.2.12 on 2020-11-02 12:24

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effortloop_group', to='otree.Session')),
            ],
            options={
                'db_table': 'effortloop_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='effortloop_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'effortloop_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('round', otree.db.models.IntegerField(null=True)),
                ('treat_main_wc', otree.db.models.LongStringField(null=True, verbose_name='For the next two minutes, we would like you to write a short essay about the last time you experienced a situation where there might have been witchcraft involved.Please be as detailed as you can. If you have time left before the two minutes are over, please continue writing about the same topic, even if you feel like you’re repeating yourself.')),
                ('treat_main_ctrl', otree.db.models.LongStringField(null=True, verbose_name='For the next two minutes, we would like you to write a short essay about a typical day in your life. Write for example about your routines, where you spend most time, who you talk to. If you have time left before the two minutes are over, please continue writing about the same topic, even if you feel like you’re repeating yourself.')),
                ('treat_main_rel', otree.db.models.LongStringField(null=True, verbose_name='For the next two minutes, we would like you to write a short essay about your beliefs and feelings about God and religion. If you are not religious, please write about what the idea of god means to you. If you have time left before the two minutes are over, please continue writing about the same topic, even if you feel like you’re repeating yourself')),
                ('nb_inserted', otree.db.models.IntegerField(null=True)),
                ('nb_correct', otree.db.models.IntegerField(null=True)),
                ('nb_display1', otree.db.models.IntegerField(null=True)),
                ('nb_display2', otree.db.models.IntegerField(null=True)),
                ('nb_display3', otree.db.models.IntegerField(null=True)),
                ('nb_display4', otree.db.models.IntegerField(null=True)),
                ('nb_display5', otree.db.models.IntegerField(null=True)),
                ('invest', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='How much do you want to invest')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='effortloop.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effortloop_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effortloop_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effortloop.Subsession')),
            ],
            options={
                'db_table': 'effortloop_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effortloop.Subsession'),
        ),
    ]
