# Generated by Django 2.2.12 on 2020-11-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nb_display5',
        ),
    ]
