# Generated by Django 2.2.12 on 2020-11-02 13:59

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0002_remove_player_nb_display5'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='treat_2_ctrl',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Remember the essay that you wrote some moments ago. Is the day that you described a typcial day in your life?'),
        ),
        migrations.AddField(
            model_name='player',
            name='treat_2_rel',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Remember the essay that you wrote some moments ago. When was the last time you thought about god or relgion??'),
        ),
        migrations.AddField(
            model_name='player',
            name='treat_2_wc',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Remember the essay that you wrote some moments ago. When was the last time you experienced such or a similar situation?'),
        ),
    ]
