# Generated by Django 2.2.12 on 2020-11-02 15:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0009_remove_player_redistribute_eff'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='redistribute_eff',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
