# Generated by Django 2.2.12 on 2020-11-02 15:39

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0010_player_redistribute_eff'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='redistribute_luck1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='redistribute_luck2',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
