# Generated by Django 2.2.12 on 2020-11-02 16:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0014_auto_20201102_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guess',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
