# Generated by Django 2.2.12 on 2020-11-03 09:09

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0016_auto_20201103_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='redistribute_eff',
        ),
        migrations.AddField(
            model_name='player',
            name='redistribute_eff1',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='redistribute_eff2',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
    ]
