# Generated by Django 2.2.12 on 2020-11-03 10:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0017_auto_20201103_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='invest_cash_main',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Cash Account'),
        ),
        migrations.AddField(
            model_name='player',
            name='invest_inv_main',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Investment Account'),
        ),
    ]
