# Generated by Django 2.2.12 on 2020-11-03 12:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0018_auto_20201103_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='q2',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Calm'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q3',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Sad'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q4',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Angry'),
        ),
    ]
