# Generated by Django 2.2.12 on 2020-11-05 11:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0020_auto_20201103_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='treat_main_ctrl',
            field=otree.db.models.LongStringField(null=True, verbose_name=''),
        ),
    ]
