# Generated by Django 2.2.12 on 2020-11-05 11:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0021_auto_20201105_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='treat_main_rel',
            field=otree.db.models.LongStringField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='treat_main_wc',
            field=otree.db.models.LongStringField(null=True, verbose_name=''),
        ),
    ]
