# Generated by Django 2.2.12 on 2020-11-06 12:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0022_auto_20201105_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='treat_3_rel',
            field=otree.db.models.IntegerField(choices=[[1, 'No one'], [2, 'Very few'], [3, 'A fair number of people'], [4, 'Most people'], [5, 'Everyone']], null=True, verbose_name='Remember the essay that you wrote some moments ago about god and religion. How many people in your village have similar views on religion as you?'),
        ),
    ]
