# Generated by Django 2.2.12 on 2020-11-06 12:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0023_auto_20201106_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='treat_3_ctrl',
            field=otree.db.models.IntegerField(choices=[[1, 'No one'], [2, 'Very few'], [3, 'A fair number of people'], [4, 'Most people'], [5, 'Everyone']], null=True, verbose_name='Remember the essay that you wrote some moments ago about a typical day in your life. How many people in your village do you think have similar days?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='treat_3_wc',
            field=otree.db.models.IntegerField(choices=[[1, 'No one'], [2, 'Very few'], [3, 'A fair number of people'], [4, 'Most people'], [5, 'Everyone']], null=True, verbose_name='Remember the essay that you wrote some moments ago about witchcraft. How many people in your village think similarly about witchcraft as you?'),
        ),
    ]
