# Generated by Django 2.2.12 on 2020-11-09 09:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0024_auto_20201106_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='treat_2_ctrl',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Remember the essay that you wrote some moments ago about a typical day in your life. Think about it carefully: Is the day that you described a typcial day in your life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='treat_2_rel',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Remember the essay that you wrote some moments ago about god and religion.Think about it carefully: Did you attend any religious meeting during the last week, such as a mass?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='treat_2_wc',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Remember the essay that you wrote some moments ago about witchcraft. Think about it carefully: Did you exprience any situation related to what you described during the last week?'),
        ),
    ]
