# Generated by Django 2.2.12 on 2020-11-09 09:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0025_auto_20201109_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='treat_2_wc',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Remember the essay that you wrote some moments ago about witchcraft. Think about it carefully: Did you experience any situation related to what you described during the last week?'),
        ),
    ]
