# Generated by Django 2.2.12 on 2020-11-11 13:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0028_auto_20201111_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='performance_main',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
