# Generated by Django 2.2.12 on 2020-11-16 09:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('effortloop', '0030_remove_player_random_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='treat_2_ctrl',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Remember the essay that you wrote some moments ago about a typical day in your life. Think about it carefully: Is the day that you described a typical day in your life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='treat_2_rel',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Remember the essay that you wrote some moments ago about God and religion. Think about it carefully: Did you attend any religious meeting during the last week?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='treat_3_rel',
            field=otree.db.models.IntegerField(choices=[[1, 'No one'], [2, 'Very few'], [3, 'A fair number of people'], [4, 'Most people'], [5, 'Everyone']], null=True, verbose_name='Remember the essay that you wrote some moments ago about God and religion. Think about it carefully: How many people in your country have similar views on religion as you?'),
        ),
    ]
