# Generated by Django 2.2.12 on 2020-11-02 13:39

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_player_redistribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='redistribution',
        ),
        migrations.AddField(
            model_name='player',
            name='redis',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
