# Generated by Django 2.2.12 on 2020-11-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0004_auto_20201102_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q16',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q17',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q18',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q19',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q20',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q9',
        ),
    ]
