# Generated by Django 2.2.12 on 2020-11-03 08:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0006_auto_20201103_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='performance_guess',
            field=otree.db.models.IntegerField(choices=[[1, 'Lowest amount'], [2, ''], [3, ''], [4, ''], [5, 'Average amount'], [6, ''], [7, ''], [8, ''], [9, ''], [10, 'Highest amount']], null=True),
        ),
    ]
