# Generated by Django 2.2.12 on 2020-11-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0009_auto_20201103_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='investment_training',
        ),
    ]
