# Generated by Django 2.2.12 on 2020-11-04 12:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0010_remove_player_investment_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='invest_cash_tr',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='invest_inv_tr',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name=''),
        ),
    ]
