# Generated by Django 2.2.12 on 2020-11-11 12:45

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0016_auto_20201109_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='payoff_tr',
        ),
        migrations.AddField(
            model_name='player',
            name='performance_tr',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
