# Generated by Django 2.2.12 on 2020-11-02 12:24

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_group', to='otree.Session')),
            ],
            options={
                'db_table': 'questionnaire_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'questionnaire_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('q1', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Afraid')),
                ('q2', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Active')),
                ('q3', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Nervous')),
                ('q4', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Calm')),
                ('q5', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Surprised')),
                ('q6', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Scared')),
                ('q7', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Inspired')),
                ('q8', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Energetic')),
                ('q9', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Strong')),
                ('q10', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Happy')),
                ('q11', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Alert')),
                ('q12', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Nervous')),
                ('q13', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Timid')),
                ('q14', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Hostile')),
                ('q15', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Enthusiastic')),
                ('q16', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Blameworthy')),
                ('q17', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Guilty')),
                ('q18', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Confident')),
                ('q19', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Hostile')),
                ('q20', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='lonely')),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='What is your age?')),
                ('gender', otree.db.models.BooleanField(choices=[[False, 'Female'], [True, 'Male']], null=True, verbose_name='What is your gender?')),
                ('education', otree.db.models.IntegerField(choices=[[1, 'No education'], [2, 'Primary education'], [3, 'Secondary education'], [4, 'Tertiary education']], null=True, verbose_name='What is the highest level of education you completed?')),
                ('religion', otree.db.models.IntegerField(choices=[[1, 'Atheist'], [2, 'Catholic'], [3, 'Protestant'], [4, 'Muslim']], null=True, verbose_name='What comes closest to describe your religious orientation')),
                ('witchcraft', otree.db.models.IntegerField(choices=[[1, 'Very weak'], [2, 'Weak'], [3, 'Neither believe or disbelieve'], [4, 'Strong'], [5, 'Very strong']], null=True, verbose_name='How strongly do you believe in witchcraft?')),
                ('ethnicity', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What is your ethnicity?')),
                ('ethnicity_strength', otree.db.models.StringField(max_length=10000, null=True, verbose_name='How important is your ethnicity to you?')),
                ('rural', otree.db.models.BooleanField(choices=[[True, 'Rural'], [False, 'Urban']], null=True, verbose_name='Do you live in an urban (city) or a rural area (village, town)?')),
                ('employment', otree.db.models.IntegerField(choices=[[1, 'Unemployed'], [2, 'Student'], [3, 'Self-employed'], [4, 'Wage-employed'], [5, 'Retired']], null=True, verbose_name='What best describes your employment status?')),
                ('occupation', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name="What is your current occupation? (If you currently don't have an occupation, enter your last occupation. If you never had a occupation, leave this field blank.)")),
                ('income', otree.db.models.IntegerField(choices=[[1, 'Below XX'], [2, '...'], [3, '...'], [4, 'More than XXX']], null=True, verbose_name='In which range is your yearly household income?')),
                ('happy', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Please imagine a ladder with steps numbered from zero at the bottom to ten at the top. Suppose we say that the top of the ladder represents the best possible life for you and the bottom of the ladder represents the worst possible life for you. If the top step is 10 and the bottom step is 0, on which step of the ladder do you feel you personally stand at the present time?')),
                ('check_one', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please briefly speculate about what this study is about. (A word is enough)')),
                ('check_two', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Have you read about a study that does similar tasks as the ones you completed today?')),
                ('check_three', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Has there been anything that you do not understand or find odd about this study?')),
                ('feedback', otree.db.models.LongStringField(blank=True, null=True, verbose_name='Do you have any oher feedback about the study?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subsession')),
            ],
            options={
                'db_table': 'questionnaire_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subsession'),
        ),
    ]
