# Generated by Django 2.2.12 on 2020-11-03 13:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q16',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q17',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q18',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q19',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q20',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q9',
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=otree.db.models.IntegerField(null=True, verbose_name='On a scale of 1-5, 1 being very good and 5 being very bad'),
        ),
    ]
