# Generated by Django 2.2.12 on 2020-11-03 13:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20201103_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='health',
            field=otree.db.models.IntegerField(choices=[[1, 'Very good'], [2, 'Good'], [3, '...'], [4, 'More than XXX'], [5, 'Very bad']], null=True, verbose_name='On a scale of 1-5, 1 being very good and 5 being very bad. How is your health in general?'),
        ),
    ]
