# Generated by Django 2.2.12 on 2020-11-03 13:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20201103_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='health',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='On a scale of 1-5, 1 being very good and 5 being very bad. How is your health in general?'),
        ),
    ]
