# Generated by Django 2.2.12 on 2020-11-03 13:03

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20201103_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='marstat',
            field=otree.db.models.IntegerField(choices=[[1, 'Single'], [2, ''], [3, ''], [4, '']], null=True, verbose_name='What is your marial status?'),
        ),
    ]
