# Generated by Django 2.2.12 on 2020-11-03 13:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_player_marstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='marstat',
            field=otree.db.models.IntegerField(choices=[[1, 'Single'], [2, 'Couple'], [3, 'Married'], [4, 'Separated/Divorced'], [5, 'Widow/Widower']], null=True, verbose_name='What is your marial status?'),
        ),
    ]
