# Generated by Django 2.2.12 on 2020-11-05 12:45

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20201105_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='religion',
            field=otree.db.models.IntegerField(choices=[[1, 'Christian - African Independent Church'], [2, 'Christian - Pentecoastal'], [3, 'Christian - Catholic Church'], [4, 'Christian - Other'], [5, 'Traditional African religion'], [6, 'Islam'], [7, 'Jewish'], [8, 'Other religion'], [9, 'No religion']], null=True, verbose_name='What comes closest to describe your religious orientation'),
        ),
    ]
