# Generated by Django 2.2.12 on 2020-11-05 12:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20201105_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ethnicity',
        ),
        migrations.AddField(
            model_name='player',
            name='language',
            field=otree.db.models.StringField(choices=[[1, 'English'], [2, 'Zulu'], [3, 'Xhosa'], [4, 'Afrikaans'], [5, 'Sepedi'], [6, 'Tswana'], [7, 'Sotho']], max_length=10000, null=True, verbose_name='What is your first language?'),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=otree.db.models.BooleanField(choices=[[False, 'Other'], [True, 'South Africa']], null=True, verbose_name='What is your nationality?'),
        ),
    ]
