# Generated by Django 2.2.12 on 2020-11-09 09:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20201109_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='check_one',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='What do you think this study .'),
        ),
    ]
