# Generated by Django 2.2.12 on 2020-11-09 09:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_auto_20201109_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='check_one',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='What do you think this study was about?. A short answer, such as one word, is enough.'),
        ),
    ]
