# Generated by Django 2.2.12 on 2020-11-09 09:59

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0021_auto_20201109_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='trust',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name=''),
        ),
    ]
