# Generated by Django 2.2.12 on 2020-11-09 10:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0022_auto_20201109_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='trust',
            field=otree.db.models.BooleanField(choices=[[True, 'Rural'], [False, 'You can`t be too careful']], null=True, verbose_name='Generally speaking, would you say that most people can be trusted or that you need to be very careful in dealing with people?'),
        ),
    ]
