# Generated by Django 2.2.12 on 2020-11-16 09:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0029_auto_20201112_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='happy',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Imagine a ladder with steps numbered from one at the bottom to ten at the top. The top of the ladder represents the best possible life for you and the bottom of the ladder represents the worst possible life for you. On which step of the ladder do you feel you personally stand at the present time?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='marstat',
            field=otree.db.models.IntegerField(choices=[[1, 'Single'], [2, 'Couple'], [3, 'Married'], [4, 'Separated/Divorced'], [5, 'Widow/Widower']], null=True, verbose_name='What is your marital status?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='religion',
            field=otree.db.models.IntegerField(choices=[[1, 'Christian - African Independent Church'], [2, 'Christian - Pentecoastal'], [3, 'Christian - Catholic Church'], [4, 'Christian - Other'], [5, 'Traditional African religion'], [6, 'Islam'], [7, 'Jewish'], [8, 'Other religion'], [9, 'No religion']], null=True, verbose_name='What comes closest to describing your religious orientation'),
        ),
        migrations.AlterField(
            model_name='player',
            name='religion_int',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Very weak'], [2, 'Weak'], [3, 'Moderate'], [4, 'Strong'], [5, 'Very strong']], null=True, verbose_name="How strongly do you believe in this religion? If you answered 'No religion' in the previous question, you can leaves this question empty"),
        ),
        migrations.AlterField(
            model_name='player',
            name='witchcraft',
            field=otree.db.models.IntegerField(choices=[[1, 'Very weak'], [2, 'Weak'], [3, 'Moderate'], [4, 'Strong'], [5, 'Very strong']], null=True, verbose_name='How strongly do you believe in witchcraft?'),
        ),
    ]
