# Generated by Django 2.2.12 on 2020-11-16 09:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0030_auto_20201116_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='religion_int',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Very weak'], [2, 'Weak'], [3, 'Moderate'], [4, 'Strong'], [5, 'Very strong']], null=True, verbose_name="How strongly do you believe in this religion? If you answered 'No religion' in the previous question, you can leave this question empty"),
        ),
    ]
