# Generated by Django 2.2.12 on 2020-11-16 09:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0033_auto_20201116_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='witchcraft',
            field=otree.db.models.BooleanField(choices=[[False, 'No'], [True, 'Yes']], null=True, verbose_name='Do you believe in witchcraft, that is, do you believe witchcraft is possible?'),
        ),
    ]
