# Generated by Django 2.2.12 on 2020-11-16 11:34

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0034_auto_20201116_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='language',
            field=otree.db.models.IntegerField(choices=[[1, 'English'], [2, 'Zulu'], [3, 'Xhosa'], [4, 'Afrikaans'], [5, 'Sepedi'], [6, 'Tswana'], [7, 'Sotho'], [8, 'Other']], null=True, verbose_name='What is your first language?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='witchcraft_int',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Very weak'], [2, 'Weak'], [3, 'Moderate'], [4, 'Strong'], [5, 'Very strong']], null=True, verbose_name="How strongly do you believe in witchcraft? (Leave this blank, when you answered 'No' to the previous question)"),
        ),
    ]
